local_costmap:
  global_frame: odom         # 与桥接节点的output_header_frame一致
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 10.0
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  transform_tolerance: 0.5
  obstacle_range: 5.5
  raytrace_range: 8.0
  inflation_radius: 0.6
  cost_scaling_factor: 3.0
  observation_sources: scan
  scan:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    sensor_frame: base_link

